CPPFLAGS=-ansi -Wall -g -O0 -c -pedantic
LDFLAGS=-ansi -Wall -g -O0 -pedantic

all: main.cpp DFSA.cpp DPDA.cpp DFSAConfiguration.cpp DPDAConfiguration.cpp ; g++ $(LDFLAGS)  main.cpp DFSA.cpp DPDA.cpp DFSAConfiguration.cpp DPDAConfiguration.cpp -o studyComp

clean: ; rm -rf studyComp